<?php
$this->form(new \Zend\Form\Form());
//$this->form(null, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);

$title = 'Add new appointment';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="col-sm-6">
    <div class="col-sm-6">
        Teacher:
    </div>
    <div class="col-sm-6">
        <select>
            <?php foreach($teachers as $teacher) : ?>
            <option id="teachers">
                <?php echo $this->escapeHtml($teacher->first_name) . " " . $this->escapeHtml($teacher->last_name); ?>
            </option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="col-sm-6">
        Exam:
    </div>
    <div class="col-sm-6">
        <select>

        </select>
    </div>
</div>
<div class="col-sm-6">
    <?php
    $form->setAttribute('action', $this->url('appointment', array('action' => 'add')));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formCollection($form);

    //echo $this->formHidden($form->get('appointment_id'));
    //echo $this->formRow($form->get('user_id'));
    //echo $this->formRow($form->get('exam_id'));
    //echo $this->formSubmit($form->get('submit'));

    echo $this->form()->closeTag();
    ?>
</div>

<script>
        $('.datepickerthing').datetimepicker();
</script>