<?php

$title = 'Add new appointment';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('appointment', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
//echo $this->formCollection($form);

echo $this->formHidden($form->get('appointment_id'));
echo $this->formRow($form->get('user_id'));
echo $this->formRow($form->get('exam_id'));
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();