<?php
/**
 * Created by PhpStorm.
 * User: wfredrickson
 * Date: 2/25/2015
 * Time: 9:26 PM
 */

$title = 'Delete Appointment';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($appt->start_time); ?>'?
</p>
<?php
$url = $this->url('appointment', array(
    'action' => 'delete',
    'id'     => $this->appointment_id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $appt->appointment_id; ?>" />
        <input type="submit" name="del" value="Yes" class="btn btn-default" />
        <input type="submit" name="del" value="No" class="btn btn-default" />
    </div>
</form>