<?php

$title = 'My Appointments';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="btn btn-default" href="<?php echo $this->url('appointment', array('action'=>'add'));?>">Add new appointment</a>
</p>

<table class="table">
    <tr>
        <th>Appointment ID</th>
        <th>User ID</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Checkin Time</th>
        <th>Checkout Time</th>
        <th>Exam ID</th>
        <th>Seat Number</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($appointments as $appt) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($appt->appointment_id); ?></td>
            <td><?php echo $this->escapeHtml($appt->user_id);?></td>
            <td><?php echo $this->escapeHtml($appt->start_time);?></td>
            <td><?php echo $this->escapeHtml($appt->end_time);?></td>
            <td><?php echo $this->escapeHtml($appt->checkin_time); ?></td>
            <td><?php echo $this->escapeHtml($appt->checkout_time);?></td>
            <td><?php echo $this->escapeHtml($appt->exam_id);?></td>
            <td><?php echo $this->escapeHtml($appt->seat_number);?></td>
            <td>
                <a href="<?php echo $this->url('appointment',
                    array('action'=>'edit', 'id' => $appt->appointment_id));?>">Edit</a>
                <a href="<?php echo $this->url('appointment',
                    array('action'=>'delete', 'id' => $appt->appointment_id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>