<?php
/**
 * Created by PhpStorm.
 * User: wfredrickson
 * Date: 2/25/2015
 * Time: 9:25 PM
 */
$this->form(new \Zend\Form\Form());

$title = "Add new exam";
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<div>
    <?php
    $form->setAttribute('action', $this->url('exam', array('action' => 'add')));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag($form);
    ?>
</div>