<div class="container">
    <div class="row" style="margin-top:20px">
        <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
			<h1>Please Login </h1>
			<?php echo $this->escapeHtml($this->messages); ?>
			<hr/>
			<?php
			$form = $this->form;
			$form->setAttribute('action', $this->url('auth/default', array('controller' => 'index', 'action' => 'login')));
			$form->prepare();

			echo $this->form()->openTag($form);
				echo $this->formRow($form->get('usr_name'));
				echo $this->formRow($form->get('usr_password'));
				?>
				<hr/>
				<div class="controls">
					<?php
					echo $this->formRow($form->get('rememberme'));
					echo $this->formSubmit($form->get('submit'));
					?>
				</div>
			<?php
			echo $this->form()->closeTag();
			?>
			<?php // view helper
			    if ($user = $this->identity()) {
			        echo '<p class="btm-title">Logged in as ' . $this->escapeHtml($user->usr_name).'</p>';
			?>		
			| <a class="btm-title" href="<?php echo $this->url('auth/default', array('controller' => 'index', 'action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a>
			<?php
			    } else {
			        echo '<p class="btm-title">Not logged in</p>';
			    }
			?>
        </div>
    </div>
</div>