<?php

$title = 'Login';
$this->headTitle($title);
?>

<div class="container">
    <div class="row" style="margin-top:20px">
        <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            <form name="form_login" method="post" action="<?php $this->url('appointment', array('action' => 'add')) ?>" role="form">
                <fieldset>
                    <h2>Please Sign In</h2>
                    <hr class="colorgraph">
                    <div class="form-group">
                        <input name="user_id" type="text" id="user_id" class="form-control input-lg" placeholder="Email Address">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password">
                    </div>
                    <hr class="colorgraph">
                    <div class="row">
                        <div class="col-md-12">
                            <input type="submit" name="Submit" value="Login" class="btn btn-lg btn-success btn-block">
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>